CC=gcc
CFLAGS=-I.

fred: finalfred.c
	$(CC) -o fred finalfred.c $(CFLAGS)

jamy: newjamy.c
	$(CC) -o jamy newjamy.c $(CFLAGS)

sabine: truesabine.c
	$(CC) -o sabine truesabine.c $(CFLAGS)

marcel:
	./marcel.sh

clean:
	rm -f fred jamy sabine
